[wip] feat(CRATemplateRoyalNavy): Create CRA template
Royal-Navy/design-system pull request #1042
Opened 2020-06-05 10:31 UTC by m7kvqbe1

## Related issue

Closes #808 

## Overview

Create and publish custom CRA template for generating application boilerplate.

## Reason

> Application developers need a quick and easy way of getting started.

## Work carried out

- [x] Create `@royalnavy/cra-template-royalnavy` package
- [x] Add automation for publishing
- [x] Add new label to GitHub
- [ ] Test by generating new applications from template

2020-06-05 12:39 UTC, m7kvqbe1 commented
I need to publish a pre-release of this package in order to test it in the closed environment.

2020-06-13 15:25 UTC, antictor commented
Can you allow the dev to pass the --use-npm flag like the regular one? Some devs may want to use npm, I know I do for projects that don't require workspaces

2020-06-15 12:03 UTC, antictor requested changes
npm start fails due to missing Typescript.
yarnrc should be removed
Like CRA it would be better to give the option to use npm instead of yarn
After installing Typescript it then fails due to no sass.

Needs testing before a PR is raised.

2020-06-15 12:03 UTC, antictor commented on packages/cra-template-royalnavy/template/.yarnrc
> +registry "http://mirror.nelson.rn:8081/repository/npm-proxy"
I would leave this out. Light side apps will report this as an error, dark side apps have this set in the users home folder and its already set in all the docker images.

2020-06-15 13:20 UTC, m7kvqbe1 commented on packages/cra-template-royalnavy/template/.yarnrc
> +registry "http://mirror.nelson.rn:8081/repository/npm-proxy"
Both TypeScript and SASS are included as dependencies - i've just removed my global deps and I was still able to successfully generate and build a working boilerplate application.

Could you post a screenshot of the error you are getting re: missing deps.

2020-06-15 13:21 UTC, m7kvqbe1 commented on packages/cra-template-royalnavy/template/.yarnrc
> +registry "http://mirror.nelson.rn:8081/repository/npm-proxy"
`.yarnrc` has been removed.

2020-06-15 14:04 UTC, antictor approved these changes

2020-06-15 14:08 UTC, merged