feat(SidebarE): Add design documentation
Royal-Navy/design-system pull request #2257
Opened 2021-04-20 11:00 UTC by hxltrhuxze

Adds sidebarE design documentation

2021-04-20 15:08 UTC, m7kvqbe1 approved these changes

2021-04-21 08:19 UTC, thyhjwb6 requested changes
Looks good 👍 

There seems to be a mix of `top level` vs `top-level` and `the sidebar` vs `the Sidebar`. I'd also consider treating the other component names as nouns and therefore capitalising.

2021-04-21 08:19 UTC, thyhjwb6 commented on packages/docs-site/src/library/pages/components/sidebar_experimental.md
> +The sidebar component has two main sections - the main navigational area at the top of the bar, and the fixed area at the bottom of the bar.
Should this be `Sidebar`?

2021-04-21 08:19 UTC, thyhjwb6 commented on packages/docs-site/src/library/pages/components/sidebar_experimental.md
> +Only one Sidebar component should be used per page. It should contain your top level navigational items, not sub-navigational items/actions for a single page.
Should this be `top-level`?

2021-04-21 08:19 UTC, thyhjwb6 commented on packages/docs-site/src/library/pages/components/sidebar_experimental.md
> +  2. **Collapse Toggle**. Toggles the sidebar between the collapsed and expanded views.
Again `S`

2021-04-23 12:05 UTC, merged