[WIP] Feat/timeline full width
Royal-Navy/design-system pull request #2332
Opened 2021-05-05 07:49 UTC by thyhjwb6

## Related issue

#[issueid]

## Overview

[A summary of what you did in no more than one paragraph]

## Link to preview

[If you're on a project which auto-deploys branches, link to the branches preview link here]

## Reason

[Why did you do what you did? - feel free to copy from the ticket if the reason is there]

## Work carried out

[A list of work you have done, use markdown checklist format, if you leave any boxes unchecked, be sure to set this PR as a WIP]

**Example.**

- [x] A bit of work I completed
- [ ] A bit of work I did not complete

## Screenshot

[If the work is UI related then paste a screenshot of the update here.]

## Developer notes

[Sometimes, extra notes are needed to add clarity to a PR, add them here]

2021-05-11 10:28 UTC, m7kvqbe1 requested changes
🎉 

Looks great and feels really nice!

Have you tested it cross browser (mainly thinking about the window resize stuff that snapshots won't cover)?

2021-05-11 10:28 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/Timeline/hooks/useTimelineWidth.ts
> +  const timelineRef = useRef<HTMLDivElement>()
Does it make sense to supply the ref to the hook instead of the hook itself having ownership over it? 

Just thinking about future hooks/functionality that possibly also need to work with a ref.

2021-05-11 10:28 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/Timeline/hooks/useTimelineWidth.ts
> +    dispatchWidthChange()
It is arguably hidden away, but I think i'd expect the hook to initialise what it needs to implicitly anyway so I think it's probably ok imo.

2021-05-11 10:28 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/Timeline/context/reducer.ts
> +        findIndex(scaleOptions, ({ isDefault }) => isDefault)
Is there a reason to use the lodash helper over the native implementation?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex

2021-05-11 10:28 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/Timeline/TimelineGrid.tsx
> +    return null
This line is flagged by coverage report is there a test or something that covers this no rows state?

2021-05-11 10:30 UTC, m7kvqbe1 commented
Needs a rebase to make the snapshot generation work again. I had to revert a recent dependency upgrade.

2021-05-12 14:55 UTC, thyhjwb6 commented on packages/react-component-library/src/components/Timeline/hooks/useTimelineWidth.ts
> +  const timelineRef = useRef<HTMLDivElement>()
After looking at some options we will leave this as-is but keep thinking about how we will share refs with consumers.

2021-05-12 20:51 UTC, m7kvqbe1 approved these changes
👍

2021-05-13 11:01 UTC, merged