[WIP] Feat/text input experimental
Royal-Navy/design-system pull request #2459
Opened 2021-06-14 13:27 UTC by thyhjwb6

## Related issue

#[issueid]

## Overview

[A summary of what you did in no more than one paragraph]

## Link to preview

[If you're on a project which auto-deploys branches, link to the branches preview link here]

## Reason

[Why did you do what you did? - feel free to copy from the ticket if the reason is there]

## Work carried out

[A list of work you have done, use markdown checklist format, if you leave any boxes unchecked, be sure to set this PR as a WIP]

**Example.**

- [x] A bit of work I completed
- [ ] A bit of work I did not complete

## Screenshot

[If the work is UI related then paste a screenshot of the update here.]

## Developer notes

[Sometimes, extra notes are needed to add clarity to a PR, add them here]

2021-06-15 16:18 UTC, k9dh3zij commented
Thanks. Here's some feedback:



- 1. As soon as I click on the Textbox I get the following warning in the console. It doesn't throw any more errors after that, but typing is then constantly laggy for all Textboxes on the page.

`
vendors~main.1bf0c833.iframe.bundle.js:2 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at O (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:20563)
    at div
    at O (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:20563)
    at div
    at O (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:20563)
    at div
    at O (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:20563)
    at TextInputE (https://pr-2459.netlify.app/main.5d16f1ce.iframe.bundle.js:2:876547)
    at InlineStory (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4257139)
    at Story (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4258374)
    at MDXProvider (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4250323)
    at div
    at Story
    at div
    at div
    at div
    at Styled(div)
    at ZoomElement (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:1400303)
    at div
    at Styled(div)
    at div
    at Styled(div)
    at div
    at Styled(div)
    at Preview (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4278847)
    at MDXProvider (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4250323)
    at Canvas (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4290171)
    at div
    at Anchor (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4183650)
    at DocsStory (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4299506)
    at Primary (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4300720)
    at DocsPage
    at div
    at Styled(div)
    at div
    at Styled(div)
    at MDXProvider (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4250323)
    at ThemeProvider
    at SourceContainer (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4283336)
    at DocsContainer (https://pr-2459.netlify.app/vendors~main.1bf0c833.iframe.bundle.js:2:4305198)
printWarning @ vendors~main.1bf0c833.iframe.bundle.js:2
error @ vendors~main.1bf0c833.iframe.bundle.js:2
updateWrapper @ vendors~main.1bf0c833.iframe.bundle.js:2
updateProperties @ vendors~main.1bf0c833.iframe.bundle.js:2
commitUpdate @ vendors~main.1bf0c833.iframe.bundle.js:2
commitWork @ vendors~main.1bf0c833.iframe.bundle.js:2
commitMutationEffects @ vendors~main.1bf0c833.iframe.bundle.js:2
callCallback @ vendors~main.1bf0c833.iframe.bundle.js:2
nrWrapper @ iframe.html?id=text-input-experimental--with-label&viewMode=docs:128
invokeGuardedCallbackDev @ vendors~main.1bf0c833.iframe.bundle.js:2
invokeGuardedCallback @ vendors~main.1bf0c833.iframe.bundle.js:2
commitRootImpl @ vendors~main.1bf0c833.iframe.bundle.js:2
unstable_runWithPriority @ vendors~main.1bf0c833.iframe.bundle.js:2
runWithPriority$1 @ vendors~main.1bf0c833.iframe.bundle.js:2
commitRoot @ vendors~main.1bf0c833.iframe.bundle.js:2
performSyncWorkOnRoot @ vendors~main.1bf0c833.iframe.bundle.js:2
(anonymous) @ vendors~main.1bf0c833.iframe.bundle.js:2
unstable_runWithPriority @ vendors~main.1bf0c833.iframe.bundle.js:2
runWithPriority$1 @ vendors~main.1bf0c833.iframe.bundle.js:2
flushSyncCallbackQueueImpl @ vendors~main.1bf0c833.iframe.bundle.js:2
flushSyncCallbackQueue @ vendors~main.1bf0c833.iframe.bundle.js:2
flushPendingDiscreteUpdates @ vendors~main.1bf0c833.iframe.bundle.js:2
flushDiscreteUpdates @ vendors~main.1bf0c833.iframe.bundle.js:2
finishEventHandler @ vendors~main.1bf0c833.iframe.bundle.js:2
batchedEventUpdates @ vendors~main.1bf0c833.iframe.bundle.js:2
dispatchEventForPluginEventSystem @ vendors~main.1bf0c833.iframe.bundle.js:2
attemptToDispatchEvent @ vendors~main.1bf0c833.iframe.bundle.js:2
dispatchEvent @ vendors~main.1bf0c833.iframe.bundle.js:2
unstable_runWithPriority @ vendors~main.1bf0c833.iframe.bundle.js:2
runWithPriority$1 @ vendors~main.1bf0c833.iframe.bundle.js:2
discreteUpdates$1 @ vendors~main.1bf0c833.iframe.bundle.js:2
discreteUpdates @ vendors~main.1bf0c833.iframe.bundle.js:2
dispatchDiscreteEvent @ vendors~main.1bf0c833.iframe.bundle.js:2
nrWrapper @ iframe.html?id=text-input-experimental--with-label&viewMode=docs:128
Show 4 more frames
`


- 2. Hovering over *and* choosing an option from the browser autocomplete list results in a visual bug

![image](https://user-images.githubusercontent.com/73531035/122070932-42b4fc80-cdee-11eb-89f8-3e2069365088.png)

![image](https://user-images.githubusercontent.com/73531035/122071293-89a2f200-cdee-11eb-8e79-2d9da45b62e1.png)

![image](https://user-images.githubusercontent.com/73531035/122071257-80b22080-cdee-11eb-9f4c-7020b20d3575.png)



- 3. Chrome reports that the input height is 46px. However when I take a screenshot it seems to actually render at 48px tall. The input height should be 46px tall, including the default border.

![image](https://user-images.githubusercontent.com/73531035/122087941-31272100-cdfd-11eb-8f90-810982c5aa4a.png)


- 4. Adornment colour should be #3E5667

2021-06-17 12:38 UTC, thyhjwb6 commented
@k9dh3zij addressed as follows:
- console error was a pre-existing issue which has now been fixed
- select from autocomplete visual bug ✅ 
- height of component ✅ 
- adornment color ✅ 
- laggy issue has been raised in a [ticket](https://github.com/Royal-Navy/design-system/issues/2473)

2021-06-21 08:02 UTC, m7kvqbe1 requested changes
Code looks good to me but it's bizarre how slow it is when entering text (even in canvas mode in storybook).

Is it worth us creating some tests with react-hook-form? Maybe that's something we do down the line when we have a few more components to play with.

Maybe we should do some manual BrowserStack testing in other browsers?

2021-06-21 08:02 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/TextInputE/partials/StyledInput.tsx
> +  &:-webkit-autofill,
Does this need prefixing for other engines too?

2021-06-21 10:27 UTC, k9dh3zij commented
@thyhjwb6 

Thanks for looking into these. Using Chrome v 91.0.4472.106 I am still getting the visual bug with the input corners when choosing an option from auto-complete (only now they're white rather than light blue). Everything else has been resolved, thank you :) 

![image](https://user-images.githubusercontent.com/73531035/122747564-1f250280-d283-11eb-8676-1152a08ccc91.png)

![image](https://user-images.githubusercontent.com/73531035/122747608-2ea44b80-d283-11eb-845f-bfdb6c83c186.png)

![image](https://user-images.githubusercontent.com/73531035/122747926-89d63e00-d283-11eb-8674-e524d07b5d76.png)

2021-06-21 13:39 UTC, thyhjwb6 commented
@m7kvqbe1

> but it's bizarre how slow it is when entering text

This is a pre-existing issue which has been capture in a [separate ticket](https://github.com/Royal-Navy/design-system/issues/2473)

> Maybe we should do some manual BrowserStack testing in other browsers?

## ie11
![ie11](https://user-images.githubusercontent.com/56078793/122771155-13930500-d29e-11eb-9982-1fd10a10b36a.gif)

## FF
![ff](https://user-images.githubusercontent.com/56078793/122771187-1c83d680-d29e-11eb-977c-a35ced3f50de.gif)

## Edge
![edge](https://user-images.githubusercontent.com/56078793/122771224-24437b00-d29e-11eb-842d-79e2fa09b09a.gif)


@k9dh3zij thank you and fixed in latest 🙏

2021-06-22 08:40 UTC, k9dh3zij commented
All looks good from my side, thank you!

2021-06-24 08:36 UTC, m7kvqbe1 requested changes
In your IE11 gif it looks like the label text in the initial state isn't vertically centered.

Maybe it's my eyes?

2021-06-24 10:21 UTC, thyhjwb6 commented
@m7kvqbe1 it was not your 👀  .. a `fixup` has been applied

## Latest screenshots
### IE 11
![Screenshot 2021-06-24 at 11 18 54](https://user-images.githubusercontent.com/56078793/123246982-4cb9b800-d4de-11eb-91bb-606b0159ef85.png)

### Chrome
![Screenshot 2021-06-24 at 11 19 06](https://user-images.githubusercontent.com/56078793/123247015-53e0c600-d4de-11eb-98fa-711cb966414e.png)

2021-06-24 10:22 UTC, m7kvqbe1 approved these changes
👍  LGTM

2021-06-24 12:20 UTC, merged