Add `NumberInputE` v3 component
Royal-Navy/design-system pull request #2734
Opened 2021-10-22 14:35 UTC by thyhjwb6

## Related issue
Closes #2434 

## Overview
Adds the `NumberInputE` v3 component.

## Link to preview
https://numberinpute.netlify.app/?path=/story/number-input-experimental--default

## Reason
Preparing components for v3.

## Work carried out
- [x] Add component
- [x] Add condensed styles
- [x] Update component to match spec

## Screenshot
![2021-10-26 14 42 29](https://user-images.githubusercontent.com/56078793/138891514-8cedbd0e-4a85-4238-a1f1-ba2b8e949cbe.gif)

## Developer notes
- thoughts on `isCondensed` vs `small`?
- #2748 has been created for adding this to the test sandbox

2021-10-26 16:01 UTC, jpveooys reviewed
Nice work :+1:

I might need to do another pass as there's a fair bit here but wanted to submit these comments.

> thoughts on isCondensed vs small?

On 'small' vs 'condensed', small is something I would look for, and if I saw it I'd know what it meant. I don't think I'd look for condensed when thinking about size, and I'm not sure I'd know exactly what to expect if I saw `isCondensed` (it more has connotations of 'squished' to me rather than 'small').

On another topic, the design spec has this:

> As an option, you can specify that a Number input should also accept and display decimal numbers (-0.1, 0.25, 0.333).
> 
> In this case, ensure you have also defined an appropriate step.

Do we have this functionality when typing (not using the steppers)?

2021-10-26 16:01 UTC, jpveooys commented on packages/react-component-library/src/components/NumberInputE/Button.tsx
> +export const Button: React.FC<ButtonProps> = ({
Would be nice to use a more specific name for this as it's easy to confuse it for the main `Button` component when it's being used (in other files).

Some ideas:

- `NumberInputButton`
- `InlineButton`

2021-10-26 16:01 UTC, jpveooys commented on packages/react-component-library/src/components/NumberInputE/Button.tsx
> +const svgLookup = {
`svg` seems like a not too relevant implementation detail of the icons here. How about `iconLookup`?

```suggestion
const iconLookup = {
```

2021-10-26 16:01 UTC, jpveooys commented on packages/react-component-library/src/components/NumberInputE/NumberInputE.stories.tsx
> +const chromaticIgnore = { chromatic: { disable: true } }
Looks like canvas isn't used now – is this still needed?

2021-10-26 16:01 UTC, jpveooys commented on packages/react-component-library/src/components/NumberInputE/NumberInputE.test.tsx
> +    it('should display the label', () => {
Minor: Not sure we need to follow `it` by `should` all the time – could be `    it('displays the label', () => {`.

2021-10-26 16:01 UTC, jpveooys commented on packages/react-component-library/src/components/NumberInputE/NumberInputE.test.tsx
> +    describe('when', () => {
Looks like text for `describe()` is incomplete here.

2021-10-26 16:01 UTC, jpveooys commented on packages/react-component-library/src/components/NumberInputE/partials/StyledButton.tsx
> +  margin: 8px;
Use `spacing('4')`?

2021-10-26 16:01 UTC, jpveooys commented on packages/react-component-library/src/components/NumberInputE/partials/StyledButton.tsx
> +  ${({ $isDisabled }) =>
Should be able to use the disabled pseudo-class here to avoid needing to set both `$isDisabled` and `disabled` on `StyledButton`:

```
&:disabled {
  ...
}
```

(Alternatively, `disabled` is automatically made available so  `${({ disabled }) =>` should also work.)

2021-10-26 16:01 UTC, jpveooys commented on packages/react-component-library/src/components/TextInputE/partials/StyledInput.tsx
> +      return '6px 12px 6px 11px'
Should we be using `spacing()` here?

2021-10-26 16:01 UTC, jpveooys commented on packages/react-component-library/src/components/TextInputE/partials/StyledLabel.tsx
> +      return {}
`return null` should work here (`return {}` looks a bit out of place).

2021-10-27 10:07 UTC, thyhjwb6 commented on packages/react-component-library/src/components/NumberInputE/NumberInputE.stories.tsx
> +const chromaticIgnore = { chromatic: { disable: true } }
Really well spotted!

2021-10-27 12:26 UTC, thyhjwb6 commented
Thank you for the feedback @jpveooys:
- introduced `COMPONENT_SIZE` and `ComponentSizeType` for size
- the current `NumberInput` does not support decimal numbers. There is a ticket which will be done as an incremental change #1128

2021-10-27 12:46 UTC, k9dh3zij commented
Number inputs, yay! 😁  Thank you @thyhjwb6 , here is my feedback:

1. Corner radius looks smaller than design. Please use same values as TextInputE (was this fixed as I was writing this comment?! 😮)

2. Prefix and suffix font colour should be #3e5667 (Neutral 400)

3. Tab with keyboard to plus or minus button > press Enter > focus moves elsewhere, which shouldn't happen.

4. When the field gets/loses focus, the fade animation appears to happen in 'two steps'. I assume that's because the animation effects/timings are slightly different between border and shadow. Can we make sure they are the same please? Let's go for whichever is the shortest one, as they're already on the slow side. (I think this may also be the case for TextInputE - if fixing it here doesn't fix it everywhere, we should raise bugs for all other instances.)

5. Border and shadow design for the `active` state of `small` (isCondensed) size should be different to that of `forms` design. Please see spec under TextField `small` size

![image](https://user-images.githubusercontent.com/73531035/139067756-0800e938-106d-400d-abee-e05619daee85.png)

2021-10-27 14:04 UTC, jpveooys commented on packages/react-component-library/src/components/NumberInputE/partials/StyledInlineButtons.tsx
> +  &:disabled {
This one should still be using `$isDisabled` I think (no disabled state on a `div`).

2021-10-28 09:47 UTC, thyhjwb6 commented on packages/react-component-library/src/components/NumberInputE/partials/StyledInlineButtons.tsx
> +  &:disabled {
Oops! Didn't meant to leave this in 😂

2021-10-28 10:42 UTC, m7kvqbe1 requested changes
Looks awesome!!! Just minor comments really.

One UX issue I noticed is when trying to increment / decrement using keyboard controls hitting return on on of the buttons has the unwanted effect of tabbing you to the next element:

![2021-10-28 11 19 58](https://user-images.githubusercontent.com/48086589/139240366-751cc696-98d4-4c38-a304-47d74711aaa2.gif)

2021-10-28 10:42 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/NumberInputE/Input.tsx
> +        <StyledLabel
Not for now - all for the code re-use but maybe we should abstract some of these bits out into primitives?

2021-10-28 10:42 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/NumberInputE/NumberInputE.stories.tsx
> +export const Default: Story<NumberInputProps> = (props) => (
Have you seen the `Template.bind` pattern in @jpveooys `ButtonE` PR (https://github.com/defencedigital/mod-uk-design-system/pull/2733)?

2021-10-28 10:42 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/NumberInputE/NumberInputE.stories.tsx
> +import React from 'react'
Is it worth including react-hook-form and Formik usage examples in individual component story files or is this superfluous?

2021-10-28 10:42 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/NumberInputE/NumberInputE.test.tsx
> +  let onChangeSpy: (event: any) => void
Sneaky `any` here that could be gotten rid of.

2021-10-28 10:42 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/NumberInputE/NumberInputE.tsx
> +  onChange: (event: any) => void
`any`

2021-10-28 10:42 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/TextInputE/partials/StyledInput.tsx
> +      return '6px 12px 6px 11px'
Also is there a constant for `small`?

2021-10-28 11:19 UTC, thyhjwb6 commented on packages/react-component-library/src/components/NumberInputE/Input.tsx
> +        <StyledLabel
Yeah it seems to be evolving that way but would be too much for this PR.

2021-10-28 11:20 UTC, thyhjwb6 commented on packages/react-component-library/src/components/NumberInputE/NumberInputE.stories.tsx
> +import React from 'react'
I think that we have our "sandbox" examples of how to put the components into a form and individual component stories we could keep clean.

2021-10-28 12:33 UTC, thyhjwb6 commented on packages/react-component-library/src/components/TextInputE/partials/StyledInput.tsx
> +      return '6px 12px 6px 11px'
@jpveooys @m7kvqbe1:
- there was a `small` constant added in latest fixups
- `6px 12px 6px 11px` has been chosen as precision is required at px level, hence `22px 12px 6px 11px` in original code for the `forms` version

2021-10-28 14:18 UTC, thyhjwb6 commented
@k9dh3zij responses:
1. 👍 
2. 👍 
3. As agreed #2759 
4. This appears to be an issue with Storybook as I created a separate app with the component and it looks fine (see screenshot). As this rings a bell, a separate issue has been raised #2760

![2021-10-29 14 00 29](https://user-images.githubusercontent.com/56078793/139440839-dcbff4e4-3544-4626-a45c-6b8d95861488.gif)

5. 👍 

https://numberinpute.netlify.app/

2021-10-28 14:38 UTC, jpveooys commented
@thyhjwb6 Couple of failing tests on the 'Build & Test Feature / Test_react-component-library (pull_request)' build if you haven't seen them already

2021-10-28 15:38 UTC, jpveooys approved these changes

2021-10-29 12:13 UTC, k9dh3zij commented
Thanks for the fixes @thyhjwb6. 🙂
New feedback:

6. Component is now missing the light blue shadow when active (also not visible in the gif you shared above)

7. The user input (the `1000` in the example below) appears 1px lower than the middle of the input box. For reference, the `£` prefix is aligned correctly. Tested on Chrome and Safari on Mac.

![image](https://user-images.githubusercontent.com/73531035/139431745-dc905839-1d34-414b-b6d7-32bf79ec3f35.png)

 8. Not sure if this is relevant for here or if we need to change 'centrally', but `Footnote` style should be as follows:
 
![image](https://user-images.githubusercontent.com/73531035/139432095-d14ef32b-c5b1-4e3e-8274-d23a16340526.png)
Font: Lato Regular
Colour: #3e5667 (Neutral 400)
Size: 12px

Thank you!

2021-10-29 13:11 UTC, thyhjwb6 commented
@k9dh3zij 

8. gif updated 😂 
9. 👍 
10. 👍 

https://numberinpute.netlify.app/

2021-10-29 13:44 UTC, k9dh3zij commented
Thanks for updating the gif @thyhjwb6 😂
All styles look great, thank you 👍

Last one from me, sorry I wrote it on a post-it but forgot to include it earlier:

Typing an alpha character is not accepted - that's great.
However, if the cursor is not at the end of the number when I type an alpha character, all digits to the right of the cursor are deleted. It shouldn't delete any digits.

https://user-images.githubusercontent.com/73531035/139445642-3cf94bb3-0294-4d91-a068-cddc95abde73.mov

2021-11-01 10:34 UTC, thyhjwb6 commented
@k9dh3zij well spotted! As this is an issue with the existing `NumberInput` too, my recommendation is that we create a separate issue that is treated as a priority. The benefit is that we can get this piece of work through and the issue is then a smaller piece in isolation.

2021-11-02 10:11 UTC, m7kvqbe1 approved these changes
LGTM 🎉

2021-11-02 12:19 UTC, merged