[WIP] fix(Timeline): Use data control for stories
Royal-Navy/design-system pull request #2775
Opened 2021-11-02 14:57 UTC by thyhjwb6

## Related issue

#[issueid]

## Overview

[A summary of what you did in no more than one paragraph]

## Link to preview

[If you're on a project which auto-deploys branches, link to the branches preview link here]

## Reason

[Why did you do what you did? - feel free to copy from the ticket if the reason is there]

## Work carried out

[A list of work you have done, use markdown checklist format, if you leave any boxes unchecked, be sure to set this PR as a WIP]

**Example.**

- [x] A bit of work I completed
- [ ] A bit of work I did not complete

## Screenshot

[If the work is UI related then paste a screenshot of the update here.]

## Developer notes

[Sometimes, extra notes are needed to add clarity to a PR, add them here]

2021-11-22 14:40 UTC, jpveooys approved these changes
Nice one! One small comment

2021-11-22 14:40 UTC, jpveooys commented on packages/react-component-library/src/components/Timeline/__tests__/Timeline.test.tsx
> +      consoleErrorSpy = jest.spyOn(global.console, 'error')
Call `consoleErrorSpy.mockRestore()` in an `afterEach()`?

(Could turn on https://jestjs.io/docs/configuration#restoremocks-boolean, but looks like we'd need to fix some tests...)

2021-11-22 16:39 UTC, m7kvqbe1 requested changes, later dismissed
LGTM just a comment about the logging

2021-11-22 16:39 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/Timeline/Timeline.tsx
> +    console.error('`startDate` is after `endDate`')
Can we use the wrapped logger here?

 https://github.com/defencedigital/mod-uk-design-system/blob/master/packages/react-component-library/src/utils/logger.ts

2021-11-23 13:08 UTC, jpveooys approved these changes

2021-11-23 14:06 UTC, merged