[WIP] Fix/selecte typing
Royal-Navy/design-system pull request #2919
Opened 2021-12-15 20:23 UTC by thyhjwb6

## Related issue

#[issueid]

## Overview

[A summary of what you did in no more than one paragraph]

## Link to preview

[If you're on a project which auto-deploys branches, link to the branches preview link here]

## Reason

[Why did you do what you did? - feel free to copy from the ticket if the reason is there]

## Work carried out

[A list of work you have done, use markdown checklist format, if you leave any boxes unchecked, be sure to set this PR as a WIP]

**Example.**

- [x] A bit of work I completed
- [ ] A bit of work I did not complete

## Screenshot

[If the work is UI related then paste a screenshot of the update here.]

## Developer notes

[Sometimes, extra notes are needed to add clarity to a PR, add them here]

2021-12-16 10:45 UTC, k9dh3zij commented
Thanks @thyhjwb6, it behaves very well - just a couple of observations:

Comparing to the vanilla select [here](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select):

1. The timeout between keystrokes for deciding whether the user is still typing a single word or whether they've started typing a new word seems to be on the small side - not sure if there's a universally accepted 'default' and whether we should increase ours a bit?

2. If I press 'T' [wait] then press 'T' again it goes through all options starting with 'T', which is inconsistent with the vanilla Select behaviour (which sticks to the first option in the list). I think we should aim for consistency, if possible please.

2021-12-16 11:06 UTC, thyhjwb6 commented
@k9dh3zij response as follows:

1. I can look at the timing although this is out-of-the-box from a widely used library [Downshift](https://www.npmjs.com/package/downshift)
2. This behaviour is consistent with how other `select` components behave as options that begin with the same letter will be scrolled through each time the same letter is pressed. [Check the example on W3](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html)

2021-12-16 11:18 UTC, k9dh3zij commented
@thyhjwb6 Ha! That example on Mozilla broken, it randomly went through to Spider for some reason...

So as it seems this behaviour is consistent with the W3 recommended behaviour (and so it's the vanilla Select that's inconsistent), let's keep as is. The timing was just an observation and I don't have a way of reliably measuring it, so let's not worry unless we get feedback that it's confusing.

👍 from me, thank you! :)

2021-12-16 15:22 UTC, jpveooys approved these changes
Looks good to me! I noticed it still triggers the Storybook shortcuts when typing – is there anything that can be done about that?

2021-12-16 15:22 UTC, jpveooys commented on packages/react-component-library/src/components/SelectE/SelectEOption.tsx
> +>(({ badge, icon, children, isHighlighted, ...rest }, ref) => {
Hmm `ref` isn't used here. Is it meant to be forwarded, or is the forwardRef unnecessary?

2021-12-17 09:19 UTC, m7kvqbe1 requested changes
Noticed same behaviour as Anthony but code looks good - just a small comment.

2021-12-17 09:19 UTC, m7kvqbe1 commented on packages/react-component-library/src/components/SelectE/SelectE.tsx
> +    initialSelectedItem: React.Children.toArray(children).find((child) => {
Is it worth breaking some of this stuff out into functions - this code is feels a little 'cramped'.

2021-12-17 09:23 UTC, jpveooys commented
@m7kvqbe1 That looks like design tokens needs to be rebuilt to me.

2021-12-17 10:18 UTC, m7kvqbe1 approved these changes

2021-12-17 12:01 UTC, merged