docs(Storybook): Update design-guide.mdx
Royal-Navy/design-system pull request #3832
Opened 2024-06-20 14:04 UTC by PiddyD

Updated Design page

## Related issue

#[issueid]

## Overview

[A summary of what you did in no more than one paragraph]

## Link to preview

[If you're on a project which auto-deploys branches, link to the branches preview link here]

## Reason

[Why did you do what you did? - feel free to copy from the ticket if the reason is there]

## Work carried out

[A list of work you have done, use markdown checklist format, if you leave any boxes unchecked, be sure to set this PR as a WIP]

**Example.**

- [x] A bit of work I completed
- [ ] A bit of work I did not complete

## Screenshot

[If the work is UI related then paste a screenshot of the update here.]

## Developer notes

[Sometimes, extra notes are needed to add clarity to a PR, add them here]

2024-06-20 14:44 UTC, markhigham requested changes
Nice work. Some red tape to take care of too.
The PR description needs some attention. Filling out the boilerplate text etc

2024-06-20 14:44 UTC, markhigham commented on packages/react-component-library/src/intro/design-guide.mdx
> +[Download RNDS Axure Icon Library](https://www.)
Looks like a broken link?

2024-06-20 14:44 UTC, markhigham commented on packages/react-component-library/src/intro/design-guide.mdx
> +## Installing Axure libraries
there is a funky non-visible character here which prevents the heading from being rendered properly

2024-06-20 14:44 UTC, markhigham commented on packages/react-component-library/src/intro/design-guide.mdx
> +## Using RNDS library in a design file
same here is it a unicode whitespace character?

2024-06-24 09:29 UTC, m7kvqbe1 commented on packages/react-component-library/src/intro/design-guide.mdx
> +Contains RNDS Widget with ready to use interactivity.
Should this be widgets plural?

2024-06-24 13:31 UTC, markhigham approved these changes

2024-06-24 14:08 UTC, m7kvqbe1 approved these changes
LGTM

2024-06-25 05:54 UTC, merged